export const FRONTEND_URL = process?.env?.FRONTEND_URL ?? "http://localhost:5173"
export const BACKEND_URL = process?.env?.BACKEND_URL ?? "http://localhost:8080/api"
export const AUTH0_USERNAME = process?.env?.AUTH0_USERNAME ?? "pit@mail.com"
export const AUTH0_PASSWORD = process?.env?.AUTH0_PASSWORD ?? "Boca123!"
export const AUTH0_DOMAIN = process?.env?.AUTH0_DOMAIN ?? "https://dev-dxya2auaytwzj1s4.us.auth0.com"